Repository AmanSarraf/Opensource-Buddy, pull requests merged in 2022-10, with the labels that each got.

#6 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest, hacktoberfest-accepted

#13 feat: updated styling
  css/agency.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#14 Issue #5 fix: Replaced team section with contributor section
  CONTRIBUTORS.md
  index.html
  js/contributors.js
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted

#12 Updated Readme
  README.md
  img/screenshot.png
Labels: documentation, help wanted, hacktoberfest, hacktoberfest-accepted

#17 Fix visibility of Contact Section
  css/agency.css
Labels: bug, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#22 added button for blogs
  index.html
  vendor/font-awesome/css/all.min.css
  vendor/font-awesome/css/fontawesome.min.css
  vendor/font-awesome/webfonts/fa-brands-400.ttf
  vendor/font-awesome/webfonts/fa-brands-400.woff2
  vendor/font-awesome/webfonts/fa-regular-400.ttf
  vendor/font-awesome/webfonts/fa-regular-400.woff2
  vendor/font-awesome/webfonts/fa-solid-900.ttf
  vendor/font-awesome/webfonts/fa-solid-900.woff2
  vendor/font-awesome/webfonts/fa-v4compatibility.ttf
  vendor/font-awesome/webfonts/fa-v4compatibility.woff2
Labels: enhancement, help wanted, good first issue, hacktoberfest, hacktoberfest-accepted

#24 I designed a card layout, added a css file for its design and correct…
  README.md
  css/community.css
  index.html
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted

#25 Hover effect adjusted
  index.html
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted

#39 phone input box restricted to take only digit
  index.html
  js/contact_me.js
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#41 Added Favicon ico.
  index.html
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#42 Also did the suggested changes
  css/Issues_hover.css
  index.html
Labels: enhancement, help wanted, hacktoberfest, hacktoberfest-accepted

#47 Icon Removed
  index.html
  vendor/font-awesome/css/font-awesome.css
  vendor/font-awesome/css/font-awesome.min.css
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#58 Remove Extra contributors name from contributors.md
  CONTRIBUTORS.md
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#60 Bug fixed #53
  index.html
Labels: bug, good first issue, hacktoberfest, hacktoberfest-accepted

#65 changed opensource programs background color
  css/agency.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#61 Added my data
  Resources.md
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#67 Program icon added
  index.html
Labels: bug, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#75 changes
  css/agency.css
  index.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#79 change height of header
  css/agency.css
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#82 Issue #43 Making the site more consistent among smaller screen sizes.
  css/agency.css
  index.html
Labels: bug, enhancement, help wanted, hacktoberfest, hacktoberfest-accepted, important

#84 changed screenshot
  img/screenshot.png
Labels: good first issue

#83 Issue 51 Adding contributors to site with links to profile
  css/agency.css
  index.html
Labels: duplicate, enhancement, hacktoberfest, hacktoberfest-accepted
